[tox]
envlist = py{39,310,311,312,313,314}
requires = tox-uv>=1

[testenv]
deps = -r requirements.txt
commands = python tests/tests.py

[gh-actions]
python =
  3.9: py39
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313
  3.14: py314
