name: Publish library

on:
  push:
    tags:
      - '*'

jobs:
  check-javascript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 16.17.0
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: JS lint
        run: |
          cd frontend
          npm run lint

      - name: Build JS Bundle
        run: |
          cd frontend
          npm run build

  pylint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install -q --upgrade pip
        pip install -r requirements.txt

    - name: Check with Pylint
      run: |
        pylint web_pdb

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox

  publish:
    needs:
      - check-javascript
      - pylint
      - test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: Build artifacts
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
