name: Publish library

on:
  push:
    tags:
      - '*'

jobs:
  check-javascript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 16.17.0
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: JS lint
        run: |
          cd frontend
          npm run lint

      - name: Build JS Bundle
        run: |
          cd frontend
          npm run build

  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.14
      uses: actions/setup-python@v2
      with:
        python-version: "3.14"

    - name: Install dependencies
      run: |
        python -m pip install -q --upgrade pip uv
        uv pip install --system -q -r requirements.txt

    - name: Check with ruff
      run: |
        ruff check web_pdb/*.py

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv pip install --system -q tox tox-uv tox-gh-actions
    - name: Test with tox
      run: tox

  publish:
    needs:
      - check-javascript
      - ruff
      - test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.14
      uses: actions/setup-python@v1
      with:
        python-version: "3.14"

    - name: Build artifacts
      run: |
        pip install uv
        uv pip install --system wheel, build
        python -m build

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
